### ISSUE TITLE
개발 관련 이슈

### ISSUE THREAD

**Issue by chul0721** [team-int/Backup_bot#1]
직접 봇 개발이 아닌 해석만 하는건가요?

**Comment by Tim232** [comment]
https://github.com/Xenon-Bot/xenon 이거 걍 수정만 하는건가요

**Comment by chul0721** [comment]
> https://github.com/Xenon-Bot/xenon 이거 걍 수정만 하는건가요

물어보니 그게 아니라 해석부터 하고 만든데요

**Comment by Tim232** [comment]
아 코드 해석하고 새로 만든다는거요?

**Comment by chul0721** [comment]
> 아 코드 해석하고 새로 만든다는거요?

ㅖ
